import 'json_utils.dart';

/// IPTC digital source type values used in C2PA action assertions.
enum DigitalSourceType {
  /// Explicitly empty digital source type.
  empty,

  /// Media made from data used to train an algorithmic model.
  trainedAlgorithmicData,

  /// Media captured directly by a digital device.
  digitalCapture,

  /// Media captured through computational photography or similar processing.
  computationalCapture,

  /// Media derived from scanned negative film.
  negativeFilm,

  /// Media derived from scanned positive film.
  positiveFilm,

  /// Media derived from a scanned print.
  print,

  /// Media with minor human edits to an existing asset.
  minorHumanEdits,

  /// Media with human edits to an existing asset.
  humanEdits,

  /// Composite media containing trained algorithmic media.
  compositeWithTrainedAlgorithmicMedia,

  /// Media algorithmically enhanced from an existing asset.
  algorithmicallyEnhanced,

  /// Media generated by software rather than direct capture.
  softwareImage,

  /// Media created as digital art.
  digitalArt,

  /// Media created digitally without direct capture.
  digitalCreation,

  /// Media generated from data-driven processes.
  dataDrivenMedia,

  /// Media generated by a trained algorithmic model.
  trainedAlgorithmicMedia,

  /// Media generated by an algorithmic process.
  algorithmicMedia,

  /// Media captured from a screen display.
  screenCapture,

  /// Media recorded from a virtual environment.
  virtualRecording,

  /// Media composed from multiple sources.
  composite,

  /// Composite media that includes captured content.
  compositeCapture,

  /// Composite media that includes synthetic content.
  compositeSynthetic,

  /// Source type outside the known IPTC values.
  other,
}

/// A manifest-builder intent that determines generated action semantics.
sealed class BuilderIntent {
  /// Creates a builder intent value.
  const BuilderIntent();

  /// Creates a new-work intent with an IPTC [sourceType].
  ///
  /// Builder validation rejects create manifests that contain a parent
  /// ingredient.
  const factory BuilderIntent.create(DigitalSourceType sourceType) =
      CreateIntent;

  /// Creates an edit intent for one existing parent ingredient.
  ///
  /// Builder validation requires exactly one parent ingredient.
  const factory BuilderIntent.edit() = EditIntent;

  /// Creates an update intent for preserving an existing manifest lineage.
  ///
  /// Builder validation requires exactly one parent ingredient and rejects new
  /// custom assertions, actions, resources, redactions, and extra ingredients.
  const factory BuilderIntent.update() = UpdateIntent;

  /// Decodes an intent from the JSON shape produced by [toJson].
  ///
  /// Throws [FormatException] if `type` is not `create`, `edit`, or `update`.
  factory BuilderIntent.fromJson(Map<String, Object?> json) {
    return switch (json['type']) {
      'create' => CreateIntent(
        enumByName(DigitalSourceType.values, json['sourceType']) ??
            DigitalSourceType.other,
      ),
      'edit' => const EditIntent(),
      'update' => const UpdateIntent(),
      _ => throw FormatException('Unknown builder intent: ${json['type']}'),
    };
  }

  /// Stable JSON discriminator for this intent.
  String get type;

  /// Encodes this intent as JSON-compatible data.
  Map<String, Object?> toJson();
}

/// A builder intent for creating a new asset manifestation.
final class CreateIntent extends BuilderIntent {
  /// Creates a create intent with the declared [sourceType].
  const CreateIntent(this.sourceType);

  /// IPTC digital source type written to the generated `c2pa.created` action.
  final DigitalSourceType sourceType;

  /// JSON discriminator for create intents.
  @override
  String get type => 'create';

  /// Encodes this create intent as JSON-compatible data.
  @override
  Map<String, Object?> toJson() => {
    'type': type,
    'sourceType': sourceType.name,
  };

  @override
  bool operator ==(Object other) =>
      other is CreateIntent && sourceType == other.sourceType;

  @override
  int get hashCode => Object.hash(type, sourceType);
}

/// A builder intent for editing one parent ingredient.
final class EditIntent extends BuilderIntent {
  /// Creates an edit intent.
  const EditIntent();

  /// JSON discriminator for edit intents.
  @override
  String get type => 'edit';

  /// Encodes this edit intent as JSON-compatible data.
  @override
  Map<String, Object?> toJson() => {'type': type};

  @override
  bool operator ==(Object other) => other is EditIntent;

  @override
  int get hashCode => type.hashCode;
}

/// A builder intent for updating an existing parent manifest in place.
final class UpdateIntent extends BuilderIntent {
  /// Creates an update intent.
  const UpdateIntent();

  /// JSON discriminator for update intents.
  @override
  String get type => 'update';

  /// Encodes this update intent as JSON-compatible data.
  @override
  Map<String, Object?> toJson() => {'type': type};

  @override
  bool operator ==(Object other) => other is UpdateIntent;

  @override
  int get hashCode => type.hashCode;
}

/// Ingredient relationship values used in ingredient assertions.
enum Relationship {
  /// The ingredient is the parent asset of the new manifest.
  parentOf,

  /// The ingredient is a component used in the new asset.
  componentOf,

  /// The ingredient is an input consumed to create the new asset.
  inputTo,
}

/// C2PA claim version discriminator.
enum ClaimVersion {
  /// C2PA claim version 1.
  v1(1),

  /// C2PA claim version 2.
  v2(2);

  /// Creates a claim version with its numeric CBOR value.
  const ClaimVersion(this.number);

  /// Numeric version value used in serialized claim metadata.
  final int number;

  /// Decodes a claim version from a number or enum-name string.
  ///
  /// Returns `null` when [value] is not a known version number or name.
  static ClaimVersion? fromJson(Object? value) {
    for (final version in values) {
      if (value == version.number || value == version.name) return version;
    }
    return null;
  }
}
