/// Checks that commit messages follow Conventional Commits v1.0.0.
///
/// Usage:
///
/// ```
/// dart run tool/lint_commits.dart --range origin/main..HEAD
/// dart run tool/lint_commits.dart <sha> [<sha>...]
/// ```
///
/// Merge commits are skipped: their messages are generated by the forge rather
/// than written by the author.
library;

import 'dart:io';

import 'conventional_commits.dart';

Future<void> main(List<String> arguments) async {
  String? range;
  final shas = <String>[];
  var maxHeaderLength = 100;
  Set<String> types = defaultCommitTypes;

  for (var index = 0; index < arguments.length; index++) {
    final argument = arguments[index];
    switch (argument) {
      case '-h':
      case '--help':
        stdout.writeln(_usage);
        return;
      case '--range':
        if (index + 1 >= arguments.length) {
          _fail('--range requires a value');
          return;
        }
        range = arguments[++index];
      case '--max-header-length':
        if (index + 1 >= arguments.length) {
          _fail('--max-header-length requires a value');
          return;
        }
        final value = int.tryParse(arguments[++index]);
        if (value == null || value < 0) {
          _fail('--max-header-length must be a non-negative integer');
          return;
        }
        maxHeaderLength = value;
      case '--types':
        if (index + 1 >= arguments.length) {
          _fail('--types requires a comma separated value');
          return;
        }
        types = arguments[++index]
            .split(',')
            .map((type) => type.trim().toLowerCase())
            .where((type) => type.isNotEmpty)
            .toSet();
        if (types.isEmpty) {
          _fail('--types must name at least one type');
          return;
        }
      default:
        if (argument.startsWith('-')) {
          _fail('unknown argument: $argument');
          return;
        }
        shas.add(argument);
    }
  }

  if (range != null && shas.isNotEmpty) {
    _fail('pass either --range or explicit commit shas, not both');
    return;
  }

  final List<String> commits;
  if (range != null) {
    final resolved = await _revList(range);
    if (resolved == null) {
      _fail('could not resolve the commit range "$range"');
      return;
    }
    commits = resolved;
  } else if (shas.isNotEmpty) {
    commits = shas;
  } else {
    _fail('nothing to check; pass --range or one or more commit shas');
    return;
  }

  if (commits.isEmpty) {
    stdout.writeln('No commits to check.');
    return;
  }

  final rules = CommitRules(types: types, maxHeaderLength: maxHeaderLength);
  var offending = 0;

  for (final sha in commits) {
    final message = await _commitMessage(sha);
    if (message == null) {
      _fail('could not read the commit message for $sha');
      return;
    }

    final violations = validateCommitMessage(message, rules: rules);
    final subject = message.split('\n').first;
    if (violations.isEmpty) {
      stdout.writeln('  ok    ${_short(sha)}  $subject');
      continue;
    }

    offending++;
    stdout.writeln('  FAIL  ${_short(sha)}  $subject');
    for (final violation in violations) {
      stdout.writeln('          ${violation.rule}: ${violation.message}');
    }
  }

  stdout.writeln();
  if (offending > 0) {
    stderr.writeln(
      '$offending of ${commits.length} commit(s) do not follow '
      'Conventional Commits v1.0.0.',
    );
    stderr.writeln(
      'See https://www.conventionalcommits.org/en/v1.0.0/ . '
      'Reword with "git rebase -i" and force push, or squash merge with a '
      'conforming title.',
    );
    // Dart ignores a value returned from main, so the exit code must be set.
    exitCode = 1;
    return;
  }

  stdout.writeln(
    'All ${commits.length} commit(s) follow Conventional Commits v1.0.0.',
  );
}

const String _usage = '''
Checks that commit messages follow Conventional Commits v1.0.0.

Usage:
  dart run tool/lint_commits.dart --range <range>
  dart run tool/lint_commits.dart <sha> [<sha>...]

Options:
  --range <range>              Git revision range, such as origin/main..HEAD.
  --max-header-length <n>      Maximum description line length (0 disables).
  --types <a,b,c>              Comma separated list of allowed types.
  -h, --help                   Show this message.

Merge commits are skipped.''';

void _fail(String message) {
  stderr.writeln('error: $message');
  exitCode = 2;
}

String _short(String sha) => sha.length > 8 ? sha.substring(0, 8) : sha;

/// Lists the non-merge commits in [range], newest last.
Future<List<String>?> _revList(String range) async {
  final result = await Process.run('git', [
    'rev-list',
    '--no-merges',
    '--reverse',
    range,
  ]);
  if (result.exitCode != 0) {
    return null;
  }
  return (result.stdout as String)
      .split('\n')
      .map((line) => line.trim())
      .where((line) => line.isNotEmpty)
      .toList();
}

/// Reads the raw message body of a single commit.
Future<String?> _commitMessage(String sha) async {
  final result = await Process.run('git', ['show', '-s', '--format=%B', sha]);
  if (result.exitCode != 0) {
    return null;
  }
  return result.stdout as String;
}
